services:
  - type: web
    name: pennywise-backend
    runtime: python
    pythonVersion: 3.11
    envVars:
      - key: PATH
        value: 8000
    buildCommand: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y
      source $HOME/.cargo/env
      pip install --no-cache-dir -r requirements.txt
