services:
  - type: web
    name: pennywise-backend
    runtime: python
    pythonVersion: 3.11
    envVars:
      - key: PORT
        value: 8000
    buildCommand: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y
      export PATH="$HOME/.cargo/bin:$PATH"
      pip install --no-cache-dir -r requirements.txt
